import numpy as np
from scipy.stats import poisson, norm
import math
from numpy.typing import NDArray


class Classifier:
    def __init__(self, priors: list[float], parameters: list[dict[str, float]]):
        self.logpriors = np.log(priors)
        self.parameters = parameters
        self.category_count = len(parameters)

    def loglikelihood(
        self, inrec: tuple[float, int, int, bool], params: dict[str, float]
    ) -> float:
    # Returns the log of the likelihood that inrec would be generated by the
    # model defined by params
    ## Your code here
        area, v1, v2, felon = inrec
        area = norm.logpdf(area, loc=params["mu_a"], scale=params["std_a"])
        v1 = poisson.logpmf(v1, mu=params["lambda_v"])
        v2 = poisson.logpmf(v2, mu=params["lambda_v"])
        if felon:
            log_p_felon = np.log(params["s"])
        else:
            log_p_felon = np.log(1 - params["s"])
        return area + v1 + v2 + log_p_felon


    def predict(self, inrec: tuple) -> NDArray[np.float64]:
    # Returns a vector of the probability of each class
    # (should sum to 1.0)
    ## Your code here
        post = np.zeros(self.category_count)
        for i in range(self.category_count):
            post[i] = self.loglikelihood(inrec, self.parameters[i]) + self.logpriors[i]

        tmep = np.max(post)
        post -= tmep
        probs = np.exp(post)
        return probs / np.sum(probs)